### ISSUE TITLE
Install instructions Dockerfile fails to build

### ISSUE THREAD

**Issue by igorbrigadir** [alexklibisz/elastiknn#211]
The install instructions Dockerfile in this example https://elastiknn.com/installation/ fails to build with this error:

```Dockerfile
FROM docker.elastic.co/elasticsearch/elasticsearch:7.9.3
RUN elasticsearch-plugin install https://github.com/alexklibisz/elastiknn/releases/download/0.1.0-PRE50/elastiknn-0.1.0-PRE50_es7.9.3.zip
```

Error:

```
-> Failed installing https://github.com/alexklibisz/elastiknn/releases/download/0.1.0-PRE50/elastiknn-0.1.0-PRE50_es7.9.3.zip
-> Rolling back https://github.com/alexklibisz/elastiknn/releases/download/0.1.0-PRE50/elastiknn-0.1.0-PRE50_es7.9.3.zip
-> Rolled back https://github.com/alexklibisz/elastiknn/releases/download/0.1.0-PRE50/elastiknn-0.1.0-PRE50_es7.9.3.zip
Exception in thread "main" java.lang.IllegalStateException: unable to read from standard input; is standard input open and a tty attached?
	at org.elasticsearch.cli.Terminal$SystemTerminal.readText(Terminal.java:273)
	at org.elasticsearch.plugins.PluginSecurity.prompt(PluginSecurity.java:74)
	at org.elasticsearch.plugins.PluginSecurity.confirmPolicyExceptions(PluginSecurity.java:67)
	at org.elasticsearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.java:875)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:254)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:224)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:91)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127)
	at org.elasticsearch.cli.Command.main(Command.java:90)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)
ERROR: Service 'elasticsearch' failed to build : The command '/bin/sh -c elasticsearch-plugin install https://github.com/alexklibisz/elastiknn/releases/download/0.1.0-PRE50/elastiknn-0.1.0-PRE50_es7.9.3.zip' returned a non-zero code: 1
```

The fix is to add `-b` or `--batch` to the command https://discuss.elastic.co/t/installing-plugin-through-shell-script-without-prompt/84456/2

```Dockerfile
FROM docker.elastic.co/elasticsearch/elasticsearch:7.9.3
RUN elasticsearch-plugin install --batch https://github.com/alexklibisz/elastiknn/releases/download/0.1.0-PRE50/elastiknn-0.1.0-PRE50_es7.9.3.zip
```

**Comment by alexklibisz** [comment]
Thanks @igorbrigadir, I'll update the docs.
