### ISSUE TITLE
Error while installing version 7.12.1

### ISSUE THREAD

**Issue by ivan4github** [alexklibisz/elastiknn#268]
Hi Alex,

Being an afficionado for your plugin, I saw that 7.12.1 was just released and I jumped on it.

I am getting an error when trying to install it.
May be something is wrong on my side : 

**For the latest:**

qes@IMR-Linux /usr/software/elasticsearch/plugins $ **/usr/software/elasticsearch/bin/elasticsearch-plugin install https://github.com/alexklibisz/elastiknn/releases/latest**
warning: usage of JAVA_HOME is deprecated, use ES_JAVA_HOME
-> Installing https://github.com/alexklibisz/elastiknn/releases/latest
-> Downloading https://github.com/alexklibisz/elastiknn/releases/latest
-> Failed installing https://github.com/alexklibisz/elastiknn/releases/latest
-> Rolling back https://github.com/alexklibisz/elastiknn/releases/latest
-> Rolled back https://github.com/alexklibisz/elastiknn/releases/latest
**Exception in thread "main" java.nio.file.NoSuchFileException: /usr/software/elasticsearch/plugins/.installing-12837410611434680518/plugin-descriptor.properties**
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:373)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:424)
	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
	at java.base/java.nio.file.Files.newInputStream(Files.java:158)
	at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:173)
	at org.elasticsearch.plugins.InstallPluginCommand.loadPluginInfo(InstallPluginCommand.java:786)
	at org.elasticsearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.java:845)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:245)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:215)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:75)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:116)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:80)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:116)
	at org.elasticsearch.cli.Command.main(Command.java:79)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:36)
qes@IMR-Linux /usr/software/elasticsearch/plugins $ 

**Not luckier with the snaphot**

qes@IMR-Linux /usr/software/elasticsearch/plugins $ **/usr/software/elasticsearch/bin/elasticsearch-plugin install https://github.com/alexklibisz/elastiknn/releases**
warning: usage of JAVA_HOME is deprecated, use ES_JAVA_HOME
-> Installing https://github.com/alexklibisz/elastiknn/releases
-> Downloading https://github.com/alexklibisz/elastiknn/releases
-> Failed installing https://github.com/alexklibisz/elastiknn/releases
-> Rolling back https://github.com/alexklibisz/elastiknn/releases
-> Rolled back https://github.com/alexklibisz/elastiknn/releases
**Exception in thread "main" java.nio.file.NoSuchFileException: /usr/software/elasticsearch/plugins/.installing-13552794925094848078/plugin-descriptor.properties**
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:373)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:424)
	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
	at java.base/java.nio.file.Files.newInputStream(Files.java:158)
	at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:173)
	at org.elasticsearch.plugins.InstallPluginCommand.loadPluginInfo(InstallPluginCommand.java:786)
	at org.elasticsearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.java:845)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:245)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:215)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:75)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:116)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:80)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:116)
	at org.elasticsearch.cli.Command.main(Command.java:79)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:36)
qes@IMR-Linux /usr/software/elasticsearch/plugins $

**Comment by alexklibisz** [comment]
Hi @ivan4github , I think you might be using the wrong URL to install:

```
elasticsearch-plugin install https://github.com/alexklibisz/elastiknn/releases/latest
```

should be:

```
elasticsearch-plugin install --batch https://github.com/alexklibisz/elastiknn/releases/download/7.12.1.0/elastiknn-7.12.1.0.zip
```

**Comment by ivan4github** [comment]
Alex,

In the heat of the moment in my enthusiasm , I made this silly post.

Thank you for your kind and quick response despite the RTFM nature of it.

**Comment by alexklibisz** [comment]
No problem, glad you're finding the plugin useful!
