### ISSUE TITLE
Plugin [.installing-18148280304972249747] is missing a descriptor properties file

### ISSUE THREAD

**Issue by wysstartgo** [alexklibisz/elastiknn#516]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/alexklibisz/elastiknn/blob/main/readme.md#support)

### Background

Exception in thread "main" java.lang.IllegalStateException: Plugin [.installing-18148280304972249747] is missing a descriptor properties file.
	at org.elasticsearch.plugins.PluginDescriptor.readFromProperties(PluginDescriptor.java:199)
	at org.elasticsearch.plugins.cli.InstallPluginAction.loadPluginInfo(InstallPluginAction.java:858)
	at org.elasticsearch.plugins.cli.InstallPluginAction.installPlugin(InstallPluginAction.java:918)
	at org.elasticsearch.plugins.cli.InstallPluginAction.execute(InstallPluginAction.java:254)
	at org.elasticsearch.plugins.cli.InstallPluginCommand.execute(InstallPluginCommand.java:89)
	at org.elasticsearch.common.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:54)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:85)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:94)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:85)
	at org.elasticsearch.cli.Command.main(Command.java:50)
	at org.elasticsearch.launcher.CliToolLauncher.main(CliToolLauncher.java:64)

### Bug

bin/elasticsearch-plugin install file:///usr/share/elasticsearch/knnplugins/elastiknn-8.7.1.0.zip

### Elastiknn Version

8.7.1.0

### Platform

Docker

### Additional info

install this plugin locally

**Comment by alexklibisz** [comment]
I ran the exact docker commands from https://elastiknn.com/installation/ and everything works fine:

```bash
$ /tmp cat Dockerfile
FROM docker.elastic.co/elasticsearch/elasticsearch:8.7.1
RUN elasticsearch-plugin install --batch https://github.com/alexklibisz/elastiknn/releases/download/8.7.1.0/elastiknn-8.7.1.0.zi
$ docker build -t elastiknn-example .
...
$ docker run -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" -e "xpack.security.enabled=false" elastiknn-example
...
$ curl localhost:9200/_cat/plugins
f8b090dab225 elastiknn 8.7.1.0
```

> Steps to reproduce
> No response

Please fill out the steps to reproduce and re-open if this is still an issue.
